DROP TABLE IF EXISTS "InspectionResults" CASCADE;
DROP TABLE IF EXISTS "WorkRecords" CASCADE;
DROP TABLE IF EXISTS "ServiceRequests" CASCADE;
DROP TABLE IF EXISTS "Equipment" CASCADE;
DROP TABLE IF EXISTS "Masters" CASCADE;
DROP TABLE IF EXISTS "ClientAddresses" CASCADE;
DROP TABLE IF EXISTS "Clients" CASCADE;

CREATE TABLE "Clients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountNumber" varchar(30) NOT NULL,
    "FullName" varchar(200) NOT NULL,
    "Phone" varchar(30) NOT NULL,
    "Email" varchar(100) NOT NULL,
    "Notes" varchar(500) NOT NULL
);

CREATE TABLE "ClientAddresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId" integer NOT NULL,
    "City" varchar(100) NOT NULL,
    "Street" varchar(150) NOT NULL,
    "House" varchar(20) NOT NULL,
    "Apartment" varchar(20) NOT NULL,
    "Entrance" varchar(20) NOT NULL,
    "Floor" varchar(20) NOT NULL,
    "FullAddress" varchar(300) NOT NULL,
    CONSTRAINT "FK_ClientAddresses_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Masters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" varchar(200) NOT NULL,
    "Phone" varchar(30) NOT NULL,
    "Specialization" varchar(150) NOT NULL,
    "Qualification" varchar(100) NOT NULL,
    "IsActive" boolean NOT NULL
);

CREATE TABLE "Equipment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "SerialNumber" varchar(64) NOT NULL,
    "Type" varchar(100) NOT NULL,
    "InstallationDate" timestamp without time zone NOT NULL,
    "NextInspectionDate" timestamp without time zone NULL,
    "Manufacturer" varchar(100) NOT NULL,
    "Model" varchar(100) NOT NULL,
    "Location" varchar(200) NOT NULL,
    "Status" varchar(50) NOT NULL,
    CONSTRAINT "FK_Equipment_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Equipment_ClientAddresses_AddressId"
        FOREIGN KEY ("AddressId") REFERENCES "ClientAddresses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ServiceRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "MasterId" integer NULL,
    "RequestDate" timestamp without time zone NOT NULL,
    "DeadlineDate" timestamp without time zone NOT NULL,
    "CompletionDate" timestamp without time zone NULL,
    "RequestType" varchar(100) NOT NULL,
    "Priority" varchar(30) NOT NULL,
    "Status" varchar(50) NOT NULL,
    "Description" varchar(1000) NOT NULL,
    CONSTRAINT "FK_ServiceRequests_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ServiceRequests_ClientAddresses_AddressId"
        FOREIGN KEY ("AddressId") REFERENCES "ClientAddresses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ServiceRequests_Equipment_EquipmentId"
        FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ServiceRequests_Masters_MasterId"
        FOREIGN KEY ("MasterId") REFERENCES "Masters" ("Id") ON DELETE SET NULL
);

CREATE TABLE "WorkRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServiceRequestId" integer NOT NULL,
    "MasterId" integer NOT NULL,
    "WorkDate" timestamp without time zone NOT NULL,
    "Cost" numeric(12, 2) NOT NULL,
    "WorkType" varchar(150) NOT NULL,
    "MaterialsUsed" varchar(500) NOT NULL,
    "Result" varchar(1000) NOT NULL,
    CONSTRAINT "FK_WorkRecords_ServiceRequests_ServiceRequestId"
        FOREIGN KEY ("ServiceRequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkRecords_Masters_MasterId"
        FOREIGN KEY ("MasterId") REFERENCES "Masters" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "InspectionResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServiceRequestId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "InspectionDate" timestamp without time zone NOT NULL,
    "IsSafe" boolean NOT NULL,
    "GasLeakCheck" varchar(200) NOT NULL,
    "VentilationCheck" varchar(200) NOT NULL,
    "AutomationCheck" varchar(200) NOT NULL,
    "Conclusion" varchar(1000) NOT NULL,
    "Recommendations" varchar(1000) NOT NULL,
    CONSTRAINT "FK_InspectionResults_ServiceRequests_ServiceRequestId"
        FOREIGN KEY ("ServiceRequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InspectionResults_Equipment_EquipmentId"
        FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Clients_AccountNumber" ON "Clients" ("AccountNumber");
CREATE INDEX "IX_ClientAddresses_ClientId" ON "ClientAddresses" ("ClientId");
CREATE UNIQUE INDEX "IX_Equipment_SerialNumber" ON "Equipment" ("SerialNumber");
CREATE INDEX "IX_Equipment_ClientId" ON "Equipment" ("ClientId");
CREATE INDEX "IX_Equipment_AddressId" ON "Equipment" ("AddressId");
CREATE INDEX "IX_ServiceRequests_ClientId" ON "ServiceRequests" ("ClientId");
CREATE INDEX "IX_ServiceRequests_AddressId" ON "ServiceRequests" ("AddressId");
CREATE INDEX "IX_ServiceRequests_EquipmentId" ON "ServiceRequests" ("EquipmentId");
CREATE INDEX "IX_ServiceRequests_MasterId" ON "ServiceRequests" ("MasterId");
CREATE INDEX "IX_WorkRecords_ServiceRequestId" ON "WorkRecords" ("ServiceRequestId");
CREATE INDEX "IX_WorkRecords_MasterId" ON "WorkRecords" ("MasterId");
CREATE INDEX "IX_InspectionResults_ServiceRequestId" ON "InspectionResults" ("ServiceRequestId");
CREATE INDEX "IX_InspectionResults_EquipmentId" ON "InspectionResults" ("EquipmentId");
